version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: lms_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-lms}
      MYSQL_USER: ${MYSQL_USER:-lms}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-lmspass}
    ports:
      - "3306:3306"   # nếu trùng port local, đổi thành "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Nếu có file init SQL, mở dòng dưới:
      # - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_PASSWORD:-lmspass} --silent"]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build:
      context: ./backend/contest
      dockerfile: Dockerfile
    container_name: lms_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      # JDBC trỏ tới service "db" trong mạng docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE:-lms}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-lms}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-lmspass}

      # JPA ddl
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # Profile & port như bạn yêu cầu
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8081

      # Timezone container (tùy chỉnh nếu cần)
      TZ: Asia/Bangkok
    ports:
      - "8081:8081"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: lms_frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:80"
  #   # Nếu muốn frontend gọi backend qua cùng domain, bật proxy /api trong nginx.conf của FE.

volumes:
  mysql_data:
